imports:
    - { resource: AdminFlock/services.yml }
    - { resource: ContactFlock/services.yml }
    - { resource: UserFlock/services.yml }
    - { resource: TaxonomyFlock/services.yml }
#    - { resource: SettingsFlock/services.yaml }
    - { resource: bundles/services.yml }
