singular_name:   Alunno
plural_name:     Alunni

list_fields:
  - fullName
  - professorsEntity


blocks:
  row1:
    col1:
      size: 7
      blocks:
        alunno:
          title:  Dettagli alunno
          icon:   fa-user
          fields:
            - name
            - surname
    col2:
      size: 7
      blocks:
        insegnanti:
          title: Professori assegnati
          icon: fa-users
          fields:
            - professors



show_blocks:
  row1:
    col1:
      size: 7
      blocks:
        professore:
          title:  Dettagli professore
          icon:   fa-user
          fields:
            - fullName

        alunni:
          title: Professori assegnati
          icon: fa-users
          fields:
            - professors


fields_map:
  id:
    label:        Id
    type:         integer
    sort_by:      Student.id
    search_alias: Student.id
  name:
    label:        Nome
    type:         string
    sort_by:      Student.name
    search_alias: Student.name
  surname:
    label:        Cognome
    type:         string
    sort_by:      Student.surname
    search_alias: Student.surname
  fullName:
    label:        Nome
    type:         string
    sort_by:      Student.fullName
    search_alias: Student.fullName
  createdAt:
    label:        CreatedAt
    type:         datetime
    sort_by:      Student.createdAt
    search_alias: Student.createdAt
  updatedAt:
    label:        UpdatedAt
    type:         datetime
    sort_by:      Student.updatedAt
    search_alias: Student.updatedAt
  professors:
    label:        Professori
    type:         collection
    class:        col-6
  professorsEntity:
    label:        Professori
    type:         entity
    class:        col-6