services:
    sinervis_admin_taxonomy_menu.configure_menu_listener:
        class: App\EventListener\TaxonomyFlock\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: sinervis_admin.menu_configure, method: onMenuConfigure }
        arguments: [ "@service_container" ]