services:
    sinervis_contact_flock.configure_menu_listener:
        class: App\EventListener\ContactFlock\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: sinervis_admin.menu_configure, method: onMenuConfigure }
        arguments: [ "@service_container" ]