singular_name:   Professore
plural_name:     Professores

list_fields:
  - id
  - nome
  - cognome
  - materia
  - alumnoEntity


blocks:
  row1:
    col1:
      size: 7
      blocks:
        entity:
          title:  Dettagli
          icon:   fa-table
          fields:
            - id
            - nome
            - cognome
            - materia
            - alunni


fields_map:
  id:
    label:        Id
    type:         integer
    sort_by:      Professore.id
    search_alias: Professore.id
  nome:
    label:        Nome
    type:         string
    sort_by:      Professore.nome
    search_alias: Professore.nome
  cognome:
    label:        Cognome
    type:         string
    sort_by:      Professore.cognome
    search_alias: Professore.cognome
  materia:
    label:        Materia
    type:         string
    sort_by:      Professore.materia
    search_alias: Professore.materia
  alunni:
    label:        Alunni
    type:         collection
    class:        col-6
  alumnoEntity:
    label:        Alunni
    type:         entity
    class:        col-6

#  createdAt:
#    label:        CreatedAt
#    type:         datetime
#    sort_by:      Professore.createdAt
#    search_alias: Professore.createdAt
#  updatedAt:
#    label:        UpdatedAt
#    type:         datetime
#    sort_by:      Professore.updatedAt
#    search_alias: Professore.updatedAt
